channels:
  - conda-forge
  - defaults
dependencies:
  - altair=2.1.0
  - pandas=0.23.1
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - vega_datasets=0.5.0
  - pip=10.0.1
  - numpy=1.14.5
  - scipy=1.1.0
  - jupyterlab=0.32.1
